plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    namespace = "motif.sample.benchmark"
    compileSdkVersion 30
    buildToolsVersion "33.0.0"

    defaultConfig {
        applicationId "motif.sample.benchmark"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

kapt {
    arguments {
        // This tells Motif to generate Java code for Java sources
        arg("motif.mode", "java")
    }
}

dependencies {
    implementation project(':lib')
    kapt project(':compiler')

    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.1.0"
    implementation "androidx.appcompat:appcompat:1.3.0"
}
